---
- hosts: all
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker Service
      command: sudo systemctl start docker
      become: true
      become_user: root

    - name: Add user to Docker group
      shell: usermod -a -G docker ubuntu

    - name: Ensure Docker Container is Running
      command: docker ps | grep amitg01/insure-me:latest
      register: docker_ps
      ignore_errors: yes  # Allow failure if the container is not found  

    - name: Deploy App and Run as Container
      command: docker run -itd -p 8084:8081 amitg01/insure-me:latest
      when: docker_ps.rc != 0
